- name: Install CNI plugins
  hosts: "{{ target | default(omit) }}"
  become: true
  tasks:
    - name: Ensure CNI plugin directory exists
      ansible.builtin.file:
        path: /opt/cni/bin
        state: directory
        mode: "0755"

    - name: Check if bridge CNI plugin exists
      ansible.builtin.stat:
        path: /opt/cni/bin/bridge
      register: bridge_stat

    - name: Download CNI plugin tarball to tmp
      ansible.builtin.get_url:
        # URL is version-specific and architecture-specific
        url: https://github.com/containernetworking/plugins/releases/download/v1.7.1/cni-plugins-linux-amd64-v1.7.1.tgz
        dest: /tmp/cni-plugins.tgz
        mode: "0644"
      when: not bridge_stat.stat.exists

    - name: Extract CNI plugins
      ansible.builtin.unarchive:
        src: /tmp/cni-plugins.tgz
        dest: /opt/cni/bin
        remote_src: true
      when: not bridge_stat.stat.exists
